# Next Word Prediction

In [ ]:
faqs = """ I apologize for the confusion.
You are correct that the previous response was only 384 words, which is below the requested word count.
I will provide a more detailed essay on the cow below.
Introduction
The cow is a domesticated animal that has been an integral part of human life for centuries.
It is known as the "Cow is our Mother" in India and is considered a sacred animal in Hindu mythology.
This essay aims to provide a detailed overview of the cow, its characteristics, benefits, and significance in various aspects of human life.
Historical and Cultural Significance of the Cow
Cows have played a significant role in ancient civilizations and continue to hold cultural and religious importance in many parts of the world.
In India, the cow is revered as a sacred animal and is associated with various deities.
It has been worshipped as a goddess and is considered a symbol of wealth and abundance.
The cow is also a symbol of motherhood and nurturing, as it provides milk for human consumption.
Characteristics of Cows
Cows are known for their gentle nature and are often referred to as the "Cow is our Mother" in India.
They are herbivores, feeding on grass, leaves, and vegetables.
Cows come in various shapes, sizes, and colors, with some being small, big, white, black, or a mix of colors.
They are also known for their distinctive "moo" sound.
Benefits of Cows
Cows provide a wide range of valuable products.
The most notable of these is milk, which is a rich source of nutrition and an essential part of the human diet.
Additionally, cow dung is used as a natural fertilizer and a major source of fuel and biogas, making it a versatile and valuable resource for agricultural and energy needs.
Cows are also used for meat, leather, and other byproducts.
Economic and Agricultural Importance of Cows
Cows play a vital role in the economic and agricultural sectors.
They are used for transportation and labor in some regions, contributing to the livelihoods of many people.
The dairy industry and its various products are a source of income for numerous farmers and workers.
Cows also contribute to the sustainability of agriculture through their dung, which is used as a natural fertilizer.
Challenges Facing Cows
Despite their many benefits, cows face numerous challenges.
Environmental and health concerns related to the dairy industry, such as the use of antibiotics and hormones, have raised ethical and health concerns.
The impact of industrialization on traditional cow farming practices has also led to concerns about animal welfare and sustainability.
Future of Cows
Innovations in the dairy industry and technology have the potential to improve cow welfare and productivity.
The use of alternative sources of dairy and meat products, such as plant-based alternatives, may also reduce the environmental impact of the dairy industry.
Conclusion
In conclusion, the cow is a multifaceted and invaluable animal that has a profound impact on various aspects of human life.
Its cultural, religious, and practical significance makes it a symbol of sustenance, prosperity, and reverence.
As we continue to benefit from the various products and services that cows provide, it is essential to recognize and preserve the sacred and essential role of these gentle creatures in our world.
At the same time, we must address the challenges facing cows and work towards a sustainable and ethical future for these valuable animals. """

## Tokenizer the data

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'of': 3,
 'a': 4,
 'is': 5,
 'cows': 6,
 'in': 7,
 'cow': 8,
 'for': 9,
 'as': 10,
 'to': 11,
 'are': 12,
 'it': 13,
 'various': 14,
 'also': 15,
 'animal': 16,
 'human': 17,
 'dairy': 18,
 'that': 19,
 'provide': 20,
 'on': 21,
 'has': 22,
 'their': 23,
 'products': 24,
 'used': 25,
 'industry': 26,
 'which': 27,
 'life': 28,
 'known': 29,
 'our': 30,
 'india': 31,
 'sacred': 32,
 'its': 33,
 'benefits': 34,
 'significance': 35,
 'cultural': 36,
 'have': 37,
 'role': 38,
 'many': 39,
 'symbol': 40,
 'they': 41,
 'valuable': 42,
 'these': 43,
 'source': 44,
 'essential': 45,
 'agricultural': 46,
 'challenges': 47,
 'concerns': 48,
 'impact': 49,
 'i': 50,
 'below': 51,
 'detailed': 52,
 'essay': 53,
 'been': 54,
 'an': 55,
 'part': 56,
 'mother': 57,
 'considered': 58,
 'characteristics': 59,
 'aspects': 60,
 'continue': 61,
 'religious': 62,
 'importance': 63,
 'world': 64,
 'with': 65,
 'milk': 66,
 'gentle': 67,
 'colors': 68,
 'some': 69,
 'dung': 70,
 'natur

In [ ]:
for sentences in faqs.split('\n'):
  print(sentences)

 I apologize for the confusion.
You are correct that the previous response was only 384 words, which is below the requested word count.
I will provide a more detailed essay on the cow below.
Introduction
The cow is a domesticated animal that has been an integral part of human life for centuries.
It is known as the "Cow is our Mother" in India and is considered a sacred animal in Hindu mythology.
This essay aims to provide a detailed overview of the cow, its characteristics, benefits, and significance in various aspects of human life.
Historical and Cultural Significance of the Cow
Cows have played a significant role in ancient civilizations and continue to hold cultural and religious importance in many parts of the world.
In India, the cow is revered as a sacred animal and is associated with various deities.
It has been worshipped as a goddess and is considered a symbol of wealth and abundance.
The cow is also a symbol of motherhood and nurturing, as it provides milk for human consumpt

In [ ]:
for sentences in faqs.split('\n'):
  print(tokenizer.texts_to_sequences([sentences])[0])


[50, 87, 9, 2, 88]
[89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5, 51, 2, 97, 98, 99]
[50, 100, 20, 4, 101, 52, 53, 21, 2, 8, 51]
[102]
[2, 8, 5, 4, 103, 16, 19, 22, 54, 55, 104, 56, 3, 17, 28, 9, 105]
[13, 5, 29, 10, 2, 8, 5, 30, 57, 7, 31, 1, 5, 58, 4, 32, 16, 7, 106, 107]
[108, 53, 109, 11, 20, 4, 52, 110, 3, 2, 8, 33, 59, 34, 1, 35, 7, 14, 60, 3, 17, 28]
[111, 1, 36, 35, 3, 2, 8]
[6, 37, 112, 4, 113, 38, 7, 114, 115, 1, 61, 11, 116, 36, 1, 62, 63, 7, 39, 117, 3, 2, 64]
[7, 31, 2, 8, 5, 118, 10, 4, 32, 16, 1, 5, 119, 65, 14, 120]
[13, 22, 54, 121, 10, 4, 122, 1, 5, 58, 4, 40, 3, 123, 1, 124]
[2, 8, 5, 15, 4, 40, 3, 125, 1, 126, 10, 13, 127, 66, 9, 17, 128]
[59, 3, 6]
[6, 12, 29, 9, 23, 67, 129, 1, 12, 130, 131, 11, 10, 2, 8, 5, 30, 57, 7, 31]
[41, 12, 132, 133, 21, 134, 135, 1, 136]
[6, 137, 7, 14, 138, 139, 1, 68, 65, 69, 140, 141, 142, 143, 144, 145, 4, 146, 3, 68]
[41, 12, 15, 29, 9, 23, 147, 148, 149]
[34, 3, 6]
[6, 20, 4, 150, 151, 3, 42, 24]
[2, 152, 153, 3, 43, 5, 66, 27, 

In [ ]:
input_sequences = []
for sentences in faqs.split('\n'):
  tokenized_sentences = tokenizer.texts_to_sequences([sentences])[0]
  for i in range(1,len(tokenized_sentences)):
    n_gram = tokenized_sentences[:i+1]
    input_sequences.append(n_gram)

In [ ]:
input_sequences

[[50, 87],
 [50, 87, 9],
 [50, 87, 9, 2],
 [50, 87, 9, 2, 88],
 [89, 12],
 [89, 12, 90],
 [89, 12, 90, 19],
 [89, 12, 90, 19, 2],
 [89, 12, 90, 19, 2, 91],
 [89, 12, 90, 19, 2, 91, 92],
 [89, 12, 90, 19, 2, 91, 92, 93],
 [89, 12, 90, 19, 2, 91, 92, 93, 94],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5, 51],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5, 51, 2],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5, 51, 2, 97],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5, 51, 2, 97, 98],
 [89, 12, 90, 19, 2, 91, 92, 93, 94, 95, 96, 27, 5, 51, 2, 97, 98, 99],
 [50, 100],
 [50, 100, 20],
 [50, 100, 20, 4],
 [50, 100, 20, 4, 101],
 [50, 100, 20, 4, 101, 52],
 [50, 100, 20, 4, 101, 52, 53],
 [50, 100, 20, 4, 101, 52, 53, 21],
 [50, 100, 20, 4, 101, 52, 53, 21, 2],
 [50, 100, 20, 4, 101, 5

In [ ]:
max_len = max([len(x) for x in input_sequences])

## input output segmentations

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences,maxlen = max_len,padding = 'pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  50,  87],
       [  0,   0,   0, ...,  50,  87,   9],
       [  0,   0,   0, ...,  87,   9,   2],
       ...,
       [  0,   0,   0, ...,  84,   9,  43],
       [  0,   0,   0, ...,   9,  43,  42],
       [  0,   0,   0, ...,  43,  42, 230]], dtype=int32)

In [ ]:
x = padded_input_sequences[:,:-1]

In [ ]:
x

array([[ 0,  0,  0, ...,  0,  0, 50],
       [ 0,  0,  0, ...,  0, 50, 87],
       [ 0,  0,  0, ..., 50, 87,  9],
       ...,
       [ 0,  0,  0, ..., 82, 84,  9],
       [ 0,  0,  0, ..., 84,  9, 43],
       [ 0,  0,  0, ...,  9, 43, 42]], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
y

array([ 87,   9,   2,  88,  12,  90,  19,   2,  91,  92,  93,  94,  95,
        96,  27,   5,  51,   2,  97,  98,  99, 100,  20,   4, 101,  52,
        53,  21,   2,   8,  51,   8,   5,   4, 103,  16,  19,  22,  54,
        55, 104,  56,   3,  17,  28,   9, 105,   5,  29,  10,   2,   8,
         5,  30,  57,   7,  31,   1,   5,  58,   4,  32,  16,   7, 106,
       107,  53, 109,  11,  20,   4,  52, 110,   3,   2,   8,  33,  59,
        34,   1,  35,   7,  14,  60,   3,  17,  28,   1,  36,  35,   3,
         2,   8,  37, 112,   4, 113,  38,   7, 114, 115,   1,  61,  11,
       116,  36,   1,  62,  63,   7,  39, 117,   3,   2,  64,  31,   2,
         8,   5, 118,  10,   4,  32,  16,   1,   5, 119,  65,  14, 120,
        22,  54, 121,  10,   4, 122,   1,   5,  58,   4,  40,   3, 123,
         1, 124,   8,   5,  15,   4,  40,   3, 125,   1, 126,  10,  13,
       127,  66,   9,  17, 128,   3,   6,  12,  29,   9,  23,  67, 129,
         1,  12, 130, 131,  11,  10,   2,   8,   5,  30,  57,   

In [ ]:
x.shape,y.shape

((526, 32), (526,))

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 231)

In [ ]:
y.shape

(526, 231)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM, Dense

## Model Building

In [ ]:
model = Sequential()
model.add(Embedding(231,100,input_length = 32 ))
model.add(LSTM(150))
model.add(Dense(231,activation = 'softmax'))

In [ ]:
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 32, 100)           23100     
                                                                 
 lstm_1 (LSTM)               (None, 150)               150600    
                                                                 
 dense_1 (Dense)             (None, 231)               34881     
                                                                 
Total params: 208581 (814.77 KB)
Trainable params: 208581 (814.77 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x,y,epochs = 100)

Epoch 1/100
17/17 [==============================] - 5s 131ms/step - loss: 5.3624 - accuracy: 0.0532
Epoch 2/100
17/17 [==============================] - 2s 91ms/step - loss: 4.9651 - accuracy: 0.0703
Epoch 3/100
17/17 [==============================] - 2s 116ms/step - loss: 4.8481 - accuracy: 0.0684
Epoch 4/100
17/17 [==============================] - 2s 100ms/step - loss: 4.8120 - accuracy: 0.0722
Epoch 5/100
17/17 [==============================] - 1s 34ms/step - loss: 4.7946 - accuracy: 0.0722
Epoch 6/100
17/17 [==============================] - 1s 44ms/step - loss: 4.7779 - accuracy: 0.0722
Epoch 7/100
17/17 [==============================] - 0s 25ms/step - loss: 4.7416 - accuracy: 0.0760
Epoch 8/100
17/17 [==============================] - 1s 25ms/step - loss: 4.6978 - accuracy: 0.0722
Epoch 9/100
17/17 [==============================] - 0s 25ms/step - loss: 4.6210 - accuracy: 0.0951
Epoch 10/100
17/17 [==============================] - 0s 16ms/step - loss: 4.5276 - accuracy: 0.1

## Prediction

In [ ]:
text = 'Conclusion'
for i  in range(5):
  # tokenizer
   token_text  = tokenizer.texts_to_sequences([text])[0]
# Padding
   padded_token_text = pad_sequences([token_text],maxlen = 32,padding = 'pre')
# Predict
   pos = np.argmax(model.predict(padded_token_text))

   for word,index in tokenizer.word_index.items():
     if index == pos:
       text = text + ' ' + word

print(text)

1/1 [==============================] - 0s 22ms/step
Conclusion cows provide a wide range
