# Topics covered
1. BOW
2. Ngram
3. TFIDF
4. Word2vec

### Imortant terminologies
1. Corpus
2. Vocabulary
3. Document
4. Word

## Bag of words

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'text' : ['people watch DSwithbappy','People write commment',"Bappy watch DSwithbappy","Dswithbappy write comment"], 'output' : [1,1,0,0]})

In [ ]:
df

text  output
0   people watch DSwithbappy       1
1      People write commment       1
2    Bappy watch DSwithbappy       0
3  Dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(bow)    #sparse matrix

  (0, 4)	1
  (0, 5)	1
  (0, 3)	1
  (1, 4)	1
  (1, 6)	1
  (1, 2)	1
  (2, 5)	1
  (2, 3)	1
  (2, 0)	1
  (3, 3)	1
  (3, 6)	1
  (3, 1)	1


In [ ]:
print(cv.vocabulary_)

{'people': 4, 'watch': 5, 'dswithbappy': 3, 'write': 6, 'commment': 2, 'bappy': 0, 'comment': 1}


In [ ]:
bow.toarray()

array([[0, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0, 1]])

In [ ]:
x = cv.transform(['bappy write comment'])
print(x.toarray())

[[1 1 0 0 0 0 1]]


## N-gram

In [ ]:
df

text  output
0   people watch DSwithbappy       1
1      People write commment       1
2    Bappy watch DSwithbappy       0
3  Dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (2,2))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'people write': 3, 'write commment': 6, 'bappy watch': 0, 'dswithbappy write': 1, 'write comment': 5}


In [ ]:
print(bow.toarray())

[[0 0 1 0 1 0 0]
 [0 0 0 1 0 0 1]
 [1 0 0 0 1 0 0]
 [0 1 0 0 0 1 0]]


## TF_IDF

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'text' : ['people watch DSwithbappy','People write commment',"Bappy watch DSwithbappy","Dswithbappy write comment"], 'output' : [1,1,0,0]})


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
tfidf.fit_transform(df['text'])

<4x7 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.        , 0.49681612, 0.61366674,
        0.61366674, 0.        ],
       [0.        , 0.        , 0.66767854, 0.        , 0.52640543,
        0.        , 0.52640543],
       [0.70203482, 0.        , 0.        , 0.44809973, 0.        ,
        0.55349232, 0.        ],
       [0.        , 0.70203482, 0.        , 0.44809973, 0.        ,
        0.        , 0.55349232]])

## Word2Vec


In [1]:
import pandas as pd

messages = pd.read_csv("/content/SMSSpamCollection.txt",sep= '\t',names = ['label','message'])

In [2]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
messages.shape

(5572, 2)

In [4]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [5]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [8]:
corpus = []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [9]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500,binary = True,ngram_range = (2,2))    # top 2500 features can be used
x = cv.fit_transform(corpus).toarray()

In [11]:
x.shape

(5572, 2500)

In [12]:
y = pd.get_dummies(messages['label'])
m = y
y = y.iloc[:,1].values

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1,random_state = 42)

In [14]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_model = MultinomialNB().fit(x_train,y_train)

In [15]:
y_pred = spam_detection_model.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score,classification_report

In [17]:
score = accuracy_score(y_test,y_pred)

In [18]:
score

0.9695340501792115

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features = 2500,ngram_range = (1,2))
x = tv.fit_transform(corpus).toarray()

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1,random_state = 42)

In [21]:
from sklearn.naive_bayes import MultinomialNB
spam_detection_model = MultinomialNB().fit(x_train,y_train)

In [22]:
y_pred = spam_detection_model.predict(x_test)

In [23]:
score = accuracy_score(y_test,y_pred)
score

0.9767025089605734

In [24]:
!pip install gensim

In [25]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[--------------------------------------------------] 1.4% 23.3/1662.8MB downloaded

KeyboardInterrupt: 

In [26]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer

In [35]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')  # Download the punkt tokenizer

# Sample text data
corpus = "weather is chill and cold by the way and here in chennai it is hot and humid and i dont like the atmosphere and climate in bangalore"

# Tokenize the text into words
tokenized_text = word_tokenize(corpus.lower())  # Convert to lowercase for consistency

# Define Word2Vec model
model = Word2Vec(sentences=[tokenized_text], vector_size=100, window=5, min_count=1, workers=4)

# Training the Word2Vec model
model.train([tokenized_text], total_examples=1, epochs=10)

# Finding the vector for a specific word
word_vector = model.wv['climate']
print("Vector representation of 'word':\n", word_vector)

# Finding similar words
similar_words = model.wv.most_similar('cold', topn=5)
print("\nWords similar to 'word':\n", similar_words)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Vector representation of 'word':
 [-0.00717913  0.00128457 -0.00715261 -0.00224008  0.00374737  0.00581693
  0.00122846  0.00213948 -0.00412606  0.00719405 -0.00629095  0.00460086
 -0.00822543  0.00202014 -0.00495905 -0.00424056 -0.00308952  0.00565696
  0.00577506 -0.00501406  0.0007876  -0.0084744   0.00786224  0.00924483
 -0.00275043  0.00082591  0.00073706  0.00547069 -0.00860769  0.00058759
  0.00688466  0.0021989   0.00113624 -0.00933585  0.00847932 -0.00624385
 -0.00296525  0.00351617 -0.00077032  0.00141901  0.00180859 -0.00683473
 -0.0097467   0.00905961  0.00620849 -0.00690872  0.00339732  0.00020101
  0.00475221 -0.00711714  0.00404123  0.0043326   0.00995827 -0.00449761
 -0.00139452 -0.00732377 -0.00966818 -0.00907593 -0.00100438 -0.00649446
  0.00481902 -0.0061818   0.00255988  0.00073657 -0.0034007  -0.00095868
  0.00998109  0.00917268 -0.00448247  0.00908325 -0.00565304  0.00593603
 -0.00306358  0.00346304  0.00300876  0.00689003 -0.00237018  0.00876272
  0.00757861 -0.0