# BOW

In [44]:
import numpy as np
import pandas as pd

In [45]:
df = pd.DataFrame({"text" : ['People watch is campusx', "Campusx watch are campusx", "people write am Comment","campusx wrIte comment"], "output" : [1,1,0,0]})

In [46]:
df

text  output
0    People watch is campusx       1
1  Campusx watch are campusx       1
2    people write am Comment       0
3      campusx wrIte comment       0

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv = CountVectorizer(lowercase = True,stop_words = 'english')   # for sentiment analysis binary = True works better

In [49]:
bow = cv.fit_transform(df['text'])

In [50]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [51]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [52]:
new = cv.transform(['campusx watch and write comment of campusx'])

In [53]:
new.toarray()     # campusx is comming 2 times

array([[2, 1, 0, 1, 1]])

# N_grams


In [54]:
df

text  output
0    People watch is campusx       1
1  Campusx watch are campusx       1
2    people write am Comment       0
3      campusx wrIte comment       0

In [63]:
cv = CountVectorizer(lowercase = True,ngram_range= (2,2),stop_words = "english")

In [64]:
n_grams = cv.fit_transform(df['text'])

In [66]:
cv.vocabulary_    # index given

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

In [68]:
new_ngram = cv.transform(['campusx watch and write comment of campusx'])

In [69]:
new_ngram.toarray()

array([[1, 0, 0, 0, 0, 1]])

# TF-IDF

In [73]:
df = pd.DataFrame({"text" : ['People watch campusx', "Campusx watch campusx", "people write Comment","campusx write comment"], "output" : [1,1,0,0]})

In [74]:
df

text  output
0   People watch campusx       1
1  Campusx watch campusx       1
2   people write Comment       0
3  campusx write comment       0

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [76]:
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [77]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


#Word2vec

## Games of thornes Dataset

In [73]:
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [74]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [72]:
!kaggle datasets download -d khulasasndh/game-of-thrones-books

  0% 0.00/3.71M [00:00<?, ?B/s]
100% 3.71M/3.71M [00:00<00:00, 148MB/s]


In [75]:
!unzip /content/game-of-thrones-books.zip

Archive:  /content/game-of-thrones-books.zip
  inflating: 001ssb.txt              
  inflating: 002ssb.txt              
  inflating: 003ssb.txt              
  inflating: 004ssb.txt              
  inflating: 005ssb.txt              


In [80]:
import nltk

In [85]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import os

story = []

# Specify the directory containing your text files
data_directory = 'data'

for filename in os.listdir(data_directory):
    file_path = os.path.join(data_directory, filename)

    with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
        corpus = file.read()

        # Use NLTK to tokenize sentences
        raw_sent = sent_tokenize(corpus)

        # Use Gensim to preprocess each sentence
        for sent in raw_sent:
            story.append(simple_preprocess(sent))

# Now 'story' contains preprocessed sentences from all the files in the specified directory


In [119]:
type(raw_sent)

list

In [87]:
len(story)

158874

In [99]:
model = gensim.models.Word2Vec(
    window = 9,
    min_count = 2,
    workers = 4
)

In [100]:
model.build_vocab(story)

In [101]:
model.train(story,total_examples=model.corpus_count,epochs = 10)

(13152370, 17250530)

In [102]:
model.wv.most_similar('daenerys')

[('stormborn', 0.7432581186294556),
 ('targaryen', 0.6951165199279785),
 ('unburnt', 0.6527866721153259),
 ('queen', 0.5806900262832642),
 ('viserys', 0.5791690349578857),
 ('aegon', 0.5764466524124146),
 ('rhaegar', 0.5688949823379517),
 ('dragons', 0.5686632394790649),
 ('elia', 0.5681307911872864),
 ('daeren', 0.5678814053535461)]

In [103]:
model.wv.similarity('arya','sansa')

0.7979455

In [104]:
model.wv.similarity('tywin',"sansa")

0.20898947

In [105]:
!kaggle datasets download -d gopinath15/friends-netflix-script-data

  0% 0.00/1.87M [00:00<?, ?B/s]
100% 1.87M/1.87M [00:00<00:00, 111MB/s]


## Friends dataset

In [106]:
!unzip /content/friends-netflix-script-data.zip

Archive:  /content/friends-netflix-script-data.zip
  inflating: Friends.csv             


In [ ]:
import pandas as pd

In [107]:
friends = pd.read_csv("/content/Friends.csv")

In [108]:
friends.head()

Text  Speaker  \
0  Originally written by Marta Kauffman and David...      NaN   
1                          Transcribed by guineapig.      NaN   
2   CENTRAL PERK. (ALL PRESENT EXCEPT RACHEL AND ...  SCENE 1   
3   There's nothing to tell! He's just some guy I...   MONICA   
4   C'mon, you're going out with the guy! There's...     JOEY   

                                             Episode     Season     Show  
0  Episode-01-The One Where Monica Gets a New Roo...  Season-01  Friends  
1  Episode-01-The One Where Monica Gets a New Roo...  Season-01  Friends  
2  Episode-01-The One Where Monica Gets a New Roo...  Season-01  Friends  
3  Episode-01-The One Where Monica Gets a New Roo...  Season-01  Friends  
4  Episode-01-The One Where Monica Gets a New Roo...  Season-01  Friends

In [110]:
story = []
for i in friends['Text']:
  story.append(i)

In [123]:
story[0]

'Originally written by Marta Kauffman and David Crane.'

In [121]:
list1 = []

In [125]:
# list1.append(simple_preprocess(sent))

from gensim.utils import simple_preprocess
for sent in story[:10]:
  list1.append(simple_preprocess(sent))


In [129]:
model = gensim.models.Word2Vec(

    window = 13,
    min_count = 2,
    workers = 5

)

In [130]:
model.build_vocab(list1)

In [131]:
model.train(list1,total_examples=model.corpus_count,epochs = 20)

(10822325, 15081260)

In [134]:
model.wv.most_similar('ross')

[('rachel', 0.6672705411911011),
 ('joey', 0.6133396625518799),
 ('monica', 0.5201127529144287),
 ('emily', 0.4997214376926422),
 ('phoebe', 0.48222947120666504),
 ('gang', 0.4701126515865326),
 ('camera', 0.4552503824234009),
 ('hallway', 0.44722622632980347),
 ('chandler', 0.4464172124862671),
 ('couch', 0.44346556067466736)]